export const ACCOUNT_TYPE = {
    SYSTEM : "SYSTEM",
    GOOGLE : "GOOGLE",
    GITHUB : "GITHUB"
}
export const SOLD = {
    SOLD_OUT : "SOLD_OUT",
    AVAILABLE : "AVAILABLE"
}
export const COMPUTER_BRANDS = {
  APPLE: "APPLE",
  DELL: "DELL",
  HP: "HP",
  LENOVO: "LENOVO",
  ASUS: "ASUS",
  ACER: "ACER",
  MSI: "MSI",
  SAMSUNG: "SAMSUNG",
  MICROSOFT: "MICROSOFT",
  RAZER: "RAZER",
  LG: "LG",
  HUAWEI: "HUAWEI"
};
export const LAPTOP_TYPES = {
  GAMING: "GAMING",
  OFFICE: "OFFICE",
  ULTRABOOK: "ULTRABOOK",
  WORKSTATION: "WORKSTATION",
  STUDENT: "STUDENT",
  BUSINESS: "BUSINESS",
  TWO_IN_ONE: "TWO_IN_ONE",
  TOUCHSCREEN: "TOUCHSCREEN",
  CREATOR: "CREATOR"
};